backend: 
    name: github
    repo: arpibb/bp-tattoo-scene

media_folder: static/assets/images
public_folder: static/assets/images

collections:
  - label: "Tattoo Artist"
    name: "artists"
    folder: "static/content/artists"
    create: true
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: Intro text, name: intro, widget: text}
      - {label: "Portrait Image", name: "portrait", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "static/content/home/home.md"
        fields:
          - {label: "Main Logo", name: "mainlogo", widget: "image"}
