backend: 
    name: github
    repo: arpibb/bp-tattoo-scene

media_folder: static/assets/images
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "static/content/home/home.md"
        fields:
          - {label: "Main Logo", name: "mainlogo", widget: "image"}
